// <auto-generated />
using System;
using FuracaoAlerta.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FuracaoAlerta.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuracaoAlerta.API.Models.Abrigo", b =>
                {
                    b.Property<int>("IdAbrigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbrigo"));

                    b.Property<int>("CapacidadeTotal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Coordenadas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("LotacaoAtual")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdAbrigo");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Abrigos");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EventoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdAlerta");

                    b.HasIndex("EventoId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEndereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Evento", b =>
                {
                    b.Property<int>("IdFuracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuracao"));

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Intensidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdFuracao");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int?>("AbrigoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("AbrigoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.UsuarioAlerta", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("AlertaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("UsuarioId", "AlertaId");

                    b.HasIndex("AlertaId");

                    b.ToTable("UsuarioAlertas");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Abrigo", b =>
                {
                    b.HasOne("FuracaoAlerta.API.Models.Endereco", "Endereco")
                        .WithMany("Abrigos")
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Alerta", b =>
                {
                    b.HasOne("FuracaoAlerta.API.Models.Evento", "Evento")
                        .WithMany("Alertas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Usuario", b =>
                {
                    b.HasOne("FuracaoAlerta.API.Models.Abrigo", "Abrigo")
                        .WithMany("Usuarios")
                        .HasForeignKey("AbrigoId");

                    b.HasOne("FuracaoAlerta.API.Models.Endereco", "Endereco")
                        .WithMany("Usuarios")
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Abrigo");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.UsuarioAlerta", b =>
                {
                    b.HasOne("FuracaoAlerta.API.Models.Alerta", "Alerta")
                        .WithMany("Usuarios")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuracaoAlerta.API.Models.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Abrigo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Alerta", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Endereco", b =>
                {
                    b.Navigation("Abrigos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Evento", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("FuracaoAlerta.API.Models.Usuario", b =>
                {
                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
